---

    - name: Install httpd
      yum: 
        name: httpd
        state: present
      when: ansible_distribution in ["Amazon", "RedHat"]

    - name: Start httpd
      service: 
        name: httpd
        state: started
      when: ansible_distribution in ["Amazon", "RedHat"]


    - name: Enable httpd
      service: 
        name: httpd
        enabled: yes
      when: ansible_distribution in ["Amazon", "RedHat"]


    - name: Install httpd
      dnf: 
        name: httpd
        state: present
      when: ansible_distribution == "CentOS"

    - name: Start httpd
      service: 
        name: httpd
        state: started
      when: ansible_distribution == "CentOS"


    - name: Enable httpd
      service: 
        name: httpd
        enabled: yes
      when: ansible_distribution == "CentOS"


    - name: Install Apache2
      apt: 
        name: apache2
        state: present
      when: ansible_distribution in ["Ubuntu", "Debian"]

    - name: Start apache2
      service: 
        name: apache2
        state: started
      when: ansible_distribution in ["Ubuntu", "Debian"]

    - name: Enable apache2
      service: 
        name: apache2
        enabled: yes
      when: ansible_distribution in ["Ubuntu", "Debian"]

... 
